name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: markdownlint
        run: |
          docker run --rm -v ${GITHUB_WORKSPACE}:/workdir \
          ghcr.io/igorshubovych/markdownlint-cli:latest \
          "/workdir/**/*.md" \
          --disable MD013 MD033 MD046 MD041 MD045 MD051 MD029 MD024
